# Generated by Django 4.2.17 on 2025-01-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_workoutlisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
    ]
